### ISSUE TITLE
Input boxes don't work

### ISSUE THREAD

**Issue by ChickCoder123** [thelegendski/thumbnail.js#3]
When I use thumbnail.js or ski.js, the <input> tag doesn't allow users to write text in them. Please fix this ASAP.

**Comment by saejin-moon** [comment]
they are fixed. move to ski.js version 1.9.x.
```html
<script src = "https://cdn.jsdelivr.net/gh/thelegendski/thumbnail.js@1.1.x/main.js"></script>
<script src = "https://cdn.jsdelivr.net/gh/thelegendski/ski.js@1.9.x/main.js"></script>
```

**Comment by ChickCoder123** [comment]
I don't want to bring any more trouble but my thumbnails are just blank. I might be using it wrong. Could you tell me if there is any bug going on right now? Should I send my code over?

**Comment by saejin-moon** [comment]
no bug if you are usin' the latest version of thumbnail.js an' ski.js, but there may be smth i missed durin' testin'. it would be appreciated if you sent your code over, :).

**Comment by ChickCoder123** [comment]
Here: https://file.io/5PN5f9aY0qM1 :)

**Comment by astro-develops** [comment]
May i ask why you sent a downloadable file instead of sending the KA link?

**Comment by ChickCoder123** [comment]
Sure. I have an unknown alt account that has the program stored in it but I don't want that to be leaked so that's why I did what I did.

**Comment by saejin-moon** [comment]
@ChickCoder123 
worked for me, v(o.o)v.
![image](https://github.com/thelegendski/thumbnail.js/assets/108815730/7800fa13-9891-4672-8da9-127066f63f74)

**Comment by saejin-moon** [comment]
btw, i fixed your code to work with `loadImage`. you have to use `onload`, or better yet, use `getImage` with asynchronous functions.
```javascript
// loadImage
enableContextMenu()
background(0)
textAlign(CENTER, 3)
fill(255)
stroke(255)
strokeWeight(1.5)
textFont('Fira Sans', 60)
text('Lazerwolf\'s', 300, 170)
text('Subpage', 300, 235)
const img = loadImage('https://cdn.kastatic.org/third_party/javascript-khansrc/live-editor/build/images/avatars/duskpin-ultimate.png')
img.onload = () => {
	imageMode(3)
	for (var i = 0; i < 5; i++) {
	    image(img, 300 + i, 390 + i, 170, 170)
	}
}
// getImage [preferred]
void async function main () {
    enableContextMenu()
    background(0)
    textAlign(CENTER, 3)
    fill(255)
    stroke(255)
    strokeWeight(1.5)
    textFont('Fira Sans', 60)
    text('Lazerwolf\'s', 300, 170)
    text('Subpage', 300, 235)
    const img = await getImage('https://cdn.kastatic.org/third_party/javascript-khansrc/live-editor/build/images/avatars/duskpin-ultimate.png')
	imageMode(3)
	for (var i = 0; i < 5; i++) {
	    image(img, 300 + i, 390 + i, 170, 170)
	}
}()
```

**Comment by ChickCoder123** [comment]
Thanks! :)

**Comment by ChickCoder123** [comment]
Actually, the thumbnail still doesn't show up. I clicked esc and the image popped up but when I save it the thumbnail is just a blank rgb(240, 240, 240) background link thing.
